### ISSUE TITLE
Validations don't work for new ScheduleEntry nested in Activity

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#1363]
When creating a new ScheduleEntry in the Picasso, the frontend currently sends a request similar to the following to the backend:
```json
{
  "title": "New activity",
  "categoryId": "9baa7a1ba884",
  "scheduleEntries": [
    {
      "number": null,
      "periodOffset": 525,
      "length": 330,
      "tmpEvent": true
    }
  ],
  "location": "Nowhere"
}
```

For one, this fails because  the nested scheduleEntry should include a `periodId`. But even when adding the `periodId` as a required field to scheduleEntry.config.php (where it is currently missing), no validations are run for the nested scheduleEntries. 

We should extend the InputFilterFactories to support validating nested entities (see https://stackoverflow.com/a/42694118 for how it can be done).

**Comment by usu** [comment]
When I ran into the issue with query params (https://github.com/ecamp/ecamp3/pull/1274#discussion_r625212771), I had that strange feeling that we will run into more issues with the fact, that validation happens in the dispatcher and not in the entity service. And here it is.

So me counterproposal would be:
Instead of apigility/API-tools (REST dispatcher), we move responsibility of validation to the (abstract) entity service. In this case we would have both ACL validation and data validation in the services, and all nested calls would go trough the checks.

Would that work? Or to much of a hassle for this case only and can solve it with the method linked by you?

**Possible alternative Option (mixed):**
We keep the validation in API-tools as is. But the entity service will figure out if it's dispatched directly from API or if it's part of a nested call. In latter case, it would load the InputFilters from API-tools config and execute them.

**Comment by carlobeltrame** [comment]
Obsoleted by the move to API platform
