### ISSUE TITLE
API platform

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#1448]
I'd like to propose to migrate the backend API from [Laminas API Tools](https://api-tools.getlaminas.org/) to [API platform](https://api-platform.com/).

> Original issue: carlobeltrame/ecamp3#1

There are many reasons for this wish. Most recently, #1220 blocks the migration to PHP 8. Also, I have looked into the Laminas project (official repos, steering committee meeting minutes, official Slack support channel), and I am underwhelmed by the community support, the feature set and the "developer experience" of Laminas.

### Now or post-MVP?
Unlike many other tech debt issues I have brought up before, I think such a migration would make the most sense **before** going live with the MVP, because of the fundamental nature of this change.

### POC
See the PR #1449

### Pros
- Symfony-based, seemingly maintained way more actively than Laminas API Tools, backed by a french software development company
- Specialized primarily on API projects, most common use cases have existing solutions
- Speaks many different API standards, including HAL, making it easier for other services to use the eCamp API
- Also doctrine-based, we can keep all our existing entity classes
- Instead of the relatively confusing and home-made `extract` / `HydrateInfo` config, uses another approach by decoupling the HAL protocol specifics from the model / DTO domain
- Can use DTOs, but don't have to
- Registration / login logic is pre-implemented
- Existing, pre-built, standards-conform, tried-and-tested systems for: PATCH operations even with nested properties, validation messages tied to fields, createdAt/updatedAt fields in the DB
- Automatic validations based on DB field settings, different validations for create and patch, as well as validations for nested entities are natively possible and will be automatically documented
- IRIs (URIs / self links) are used instead of IDs in the API to specify relations
- The correct Caching Headers are [automatically set](https://api-platform.com/docs/core/performance/). Cloudflare supports the special cache invalidation headers, but only on the Enterprise plan ._. but there are alternatives that are also supported out of the box
- Docker Setup and Helm Chart (for Kubernetes deployment) is pre-implemented (of course we still need to adapt this for ecamp)
- Things like [soft-delete](https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html), [cursor-based pagination](https://api-platform.com/docs/core/pagination/#cursor-based-pagination) and [live updates](https://api-platform.com/docs/core/mercure/) are available as pre-implemented installable /activatable bundles
- OpenAPI and other API documentation (Hydra) is built in
- PHP 8 support is built in
- There are Symfony IDE plugins for PHPStorm and VSCode

### Contras
- Another big refactoring (but with both short-term and long-term benefits)
- No slow rolling change possible, "big bang" necessary (but better now than after we've gone live)
- Some hal-json-vuex adaptations needed (`item` instead of `items`, sending the Accept header `application/hal+json` (optional), empty collection relations are omitted in responses by default, embedded collections work a little differently), most of which would make sense going forward anyways
- There are some [open issues](https://github.com/api-platform/core/search?q=hal&type=issues) about the HAL serializer. But judging by some PRs, we could contribute back fixes for most of these and they would be accepted within a reasonable timeframe.
- Authorization is preferably based on JWT tokens, not PHP session ids (but we intend to go the OAuth / OIDC way anyways in the future, and session cookies are still possible)
- I didn't find a built-in way to do Input Filters (StringTrim, StripTags), only this issue: https://github.com/api-platform/api-platform/issues/232. But I implemented a system (based on PHP 8 attributes, to make it similar in use to validations) using a [custom Denormalizer](https://api-platform.com/docs/core/serialization/#decorating-a-serializer-and-adding-extra-data), which is [mentioned](https://api-platform.com/docs/core/extending/) in the API platform documentation as the solution to "post-process objects created from the payload sent in the HTTP request body"
- ~~No support for templated links (?)~~ On the Symfony Slack, I got the input to decorate the EntrypointNormalizer.
- I haven't looked into sending Mails, but should be easily possible since some of the best PHP mail packages come from Symfony
- Print jobs infrastructure realization yet unclear (but they have [documentation](https://api-platform.com/docs/core/messenger/) for adding side effects to endpoints such as sending messages to a queue, and currently we're trying to live without print jobs anyway)
- On the community Slack channel, not all feedback is positive (especially some comments about simple use cases being simple, but custom logic being harder to implement). But neither is the feedback on the Laminas API Tools Slack channel...
- We don't have any experience with API platform yet. But it is very well documented, and there are a lot more code examples online than for Laminas.

### To consider
- The current version is 2.6. Later this year, API platform 3.0 will be released, but it will be the same as 2.7, without backward-compatibility layer. So if we start using 2.6+ now and don't use deprecated stuff, the upgrade to 3.0 should be very easy.

**Comment by usu** [comment]
Sharing my 2 cents on this.

Disclaimer ahead: I'm not particularly impressed by Laminas community management & speed of development either. 1 year ago there was much noise about the name change and how the new roof will foster development. And also how they see Mezzio as the future for API development and that some mezzio based API tooling is in the planning. Not much happened since.

I've looked at API platform earlier last year (not sure if we actually discussed in this round) and I've given it a closer look this week. I think it's an impressive platform that brings a lot along for rapid API development but also for larger and more complex use cases. And their community management seems pretty intensive as well.

Having said that, I really like to be devils advocate and throw it some challenging questions:

#### Is it the right moment?
- Which must-have MVP features depend on this change?
- Why is a transition not possible after MVP (especially if we'd switch to a solution that utilizes Doctrine as well)
- How much would this delay the MVP? (3 months? 6 months? We need to consider that development on frontend will also slow down due to resources concentrating on backend + any missing backend-feature cannot be implemented - or we have to do it twice)
- Are we ready to accept this delay?

#### Why not mezzio?
API Platform is a full stack solution. I see and understand the beauty on this, as it helps tremendously for rapid development and comes with many built-in features.
Mezzio is placed completely different, being a minimal framework working with loosely coupled modules. It utilizes and promotes standardized interfaces (PSR) wherever possible. I also see the beauty in this one, as it should be fairly easy to change/switch particular modules if they don't fit anymore.

#### Any other API frameworks that we should consider?
From what I've seen initially, there's not much code we can copy 1:1 and there's a lot that needs to be touched. If we need to this, why limiting to Doctrine? Why limiting to PHP? If we open the umbrella, are there completely different frameworks that we'd want to consider before jumping directly to API platform?


A few additional thoughts in case we'd consider doing the transition:
- Are our API end-to-end tests mature enough or do we have to strengthen them first?
- Can we refactor the code without losing the history or do we basically start from scratch?
- What do we do with the service layer? Keep as a separate logic layer or integrate into API platform structure?
- How would we do the transition practically: Finalize and agree on one endpoint first and then refactor the rest?

**Comment by carlobeltrame** [comment]
Closing in favor of #1463
