### ISSUE TITLE
Links generated by RelatedCollectionLinkNormalizer are not always urlencoded

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2289]
RelatedCollectionLinkNormalizer produces inconsistent urlencoding with link parameters.

URIs generated by the following line are not urlencoded:
https://github.com/ecamp/ecamp3/blob/devel/api/src/Serializer/Normalizer/RelatedCollectionLinkNormalizer.php#L164
```php
return $this->router->generate($this->routeNameResolver->getRouteName($relatedResourceClass, OperationType::COLLECTION), [$relatedFilterName => $this->iriConverter->getIriFromItem($object)], UrlGeneratorInterface::ABS_PATH);
```

URIs generated by this line are urlencoded:
https://github.com/ecamp/ecamp3/blob/devel/api/src/Serializer/Normalizer/RelatedCollectionLinkNormalizer.php#L143
```php
return $this->uriTemplate->expand($uriTemplate, $params);
```

We should decide for one. I believe non-encoded is the standard in HAL specification.

**Comment by carlobeltrame** [comment]
Good catch. The question is, is it safe to use unencoded URLs? I think as soon as we generate the first RelatedCollectionLink containing a user-supplied parameter instead of an IRI, it's possible to break with unencoded URLs.

Consider what would happen if for some reason we would render a link on ContentNode to other content nodes in the same camp that share the same instanceName (e.g. for a feature to find all "Schlechtwetterprogramm" content nodes in the camp):
```php
/**
 * @return ContentNode[]
 */
#[RelatedCollectionLink(ContentNode::class, ['period.camp' => 'period.camp', 'instanceName[like]' => 'instanceName'])]
public function getSimilarlyNamedContentNodes(): array { // ...
```

Normally, the generated URI would look like `/content_nodes?period.camp=/camps/1a2b3c4d&instanceName[like]=Schlechtwetterprogramm`. But if we don't urlescape the URL, a user could give a "malicious" instance name `name&period.camp=/camps/9999ffff` to a content node, and provoke a generated URI like this: `/content_nodes?period.camp=/camps/1a2b3c4d&instanceName[like]=name&period.camp=/camps/9999ffff`

In this case the worst I see happening is that the frontend and any other API clients will malfunction. But I don't see any use case for unencoded URLs either (apart from a little better readability during development). URL encoding of arbitrary URI template parameters is important, that's why the uriTemplate class does it. With urlencoding, the above example would look like `/content_nodes?period.camp=/camps/1a2b3c4d&instanceName[like]=name%26period.camp%3D%2Fcamps%2F9999ffff`.

Or are you saying, the whole outputted string, including `/content_nodes` is urlencoded by the uriTemplate class? I.e. are you saying the output of the uriTemplate class would be `%2Fcontent_nodes%3Fperiod.camp%3D%2Fcamps%2F1a2b3c4d%26instanceName%5Blike%5D%3Dname%26period.camp%3D%2Fcamps%2F9999ffff`? There I would agree with you that that's wrong.

**Comment by usu** [comment]
This is an example how a category is now returned from the API (after PR #2280):
```json
{
  "_links": {
    "self": {
      "href": "/categories/109d63083529"
    },
    "camp": {
      "href": "/camps/790f6c7a5cfa"
    },
    "preferredContentTypes": {
      "href": "/content_types?categories=/categories/109d63083529"
    },
    "rootContentNode": {
      "href": "/content_node/column_layouts/b32ca29d90fb"
    },
    "contentNodes": {
      "href": "/content_nodes?root=%2Fcontent_node%2Fcolumn_layouts%2Fb32ca29d90fb"
    }
  },
  "short": "LS",
  "name": "Lagersport",
  "color": "#4CAF50",
  "numberingStyle": "1",
  "id": "109d63083529"
}
```

- `preferredContentTypes` is a "normal" relation (`$this->router()->`...) 
- `contentNodes` is a `RelatedCollectionLink` (`$this->uriTemplate->`...).

I tried an additional `urlencode()` like this:
```php
return $this->router->generate($this->routeNameResolver->getRouteName($relatedResourceClass, OperationType::COLLECTION), [$relatedFilterName => urlencode($this->iriConverter->getIriFromItem($object))], UrlGeneratorInterface::ABS_PATH);
```

Then I ended up with some double encoded URLs in the frontend at one point. Didn't debug further, though.

**Comment by usu** [comment]
> We should decide for one. I believe non-encoded is the standard in HAL specification.

https://datatracker.ietf.org/doc/html/draft-kelly-json-hal#section-5.1:
> The "href" property is REQUIRED.
> Its value is either a URI [RFC3986] or a URI Template [RFC6570].

https://datatracker.ietf.org/doc/html/rfc3986#section-3.4:
> The characters slash ("/") and question mark ("?") may represent data
> within the query component.

> [...] one frequently used value is a reference to
> another URI, it is sometimes better for usability to avoid percent-
> encoding those characters.

In a nutshell:
- HAL links are normal URIs and should therefore of course be percent-encoded
- Surprisingly, slashes would be allowed within query parameters (both for variable name & value)

**Comment by usu** [comment]
> Then I ended up with some double encoded URLs in the frontend at one point. Didn't debug further, though.

Tried to debug on this & found the root cause behind the double encoding:
https://github.com/symfony/symfony/issues/45114
