### ISSUE TITLE
Picasso difficult to read

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3375]
Possible reason:
- The time slot 00:00 - 07:00 is empty but still shown. Occurrence counter: 1

**Comment by carlobeltrame** [comment]
The Vuetify Calendar component does not allow us to hide these hours completely.
It would be possible in the manually implemented picasso in react print (print layout #2) to hide empty hours, by modifying the [`times`](https://github.com/ecamp/ecamp3/blob/devel/frontend/src/components/print/print-react/components/picasso/Picasso.jsx#L18..L44) array.
The best range of times could also be auto-determined intelligently, based on the actual programme which is being rendered onto the picasso (i.e. automatically detect the time period in the night on which no programme and omit that period in the picasso, or set the weight of these hours very low so that they do not get allocated much vertical space).

**Comment by carlobeltrame** [comment]
Implemented in #3507 and #3887
