### ISSUE TITLE
Improve experience after creating a Camp

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3546]
When i create a new camp, i want to know that i have to first setup the Categories and Materiallists, before i start
creating activities.

After creating a camp, the user is redirected to the admin overview, and sees a popup/notification where he is informed about the proposed next steps.

**Comment by DeNic0la** [comment]
I would take this if someone could assign me, please

**Comment by manuelmeister** [comment]
I want to create some mockups first. I'll try to create them next week.

**Comment by DeNic0la** [comment]
Hey @manuelmeister 
I was wondering if those mockups are done, and then I noticed that I probably misunderstood what this issue is about.

The User is currently already redirected to the admin overview of a camp after creating it. 
I thought this issue was about displaying a text after that happens, I would have used the Toast (since it's already in the project) for that.

Also, i am not sure what you mean by that @BacLuc, Do you mean setting up the Layout of pre-created Categories before creating your own categories?
> When i create a new camp, i want to know that i have to first setup the Categories and Materiallists, before i start creating categories.

Are those requirements up to date? (there is nothing about the Block-States)
Should they be displayed if a Preset (Lagervorlage) was used?

I asked for assign to double-check that this issue is ready for implementation and to avoid two people working on the same thing, I took this issue cause it felt doable - if you prefer to do it yourself @manuelmeister I have no problem with that. If those mockups are complex that might even be better.

**Comment by BacLuc** [comment]
> Hey @manuelmeister I was wondering if those mockups are done, and then I noticed that I probably misunderstood what this issue is about.
> 
> The User is currently already redirected to the admin overview of a camp after creating it. I thought this issue was about displaying a text after that happens, I would have used the Toast (since it's already in the project) for that.

I think a toast would be too general (but lets wait for the mockups).
In the maximum variant i thought about a "tour" like https://codyhouse.co/demo/product-tour/index.html#0
Where you are guided through the setup:
1. Fill in the information
2. Create the categories you need (and define their layout and maybe even the prefilled content)
3. Create/rename/delete material lists
4. Define your progress labels

> 
> Also, i am not sure what you mean by that @BacLuc, Do you mean setting up the Layout of pre-created Categories before creating your own categories?
> 

Was this misunderstanding related to me using the wrong word at the end?
I changed it to:
When i create a new camp, i want to know that i have to first setup the Categories and Materiallists, before i start
creating ~~categories~~ activities.

> > When i create a new camp, i want to know that i have to first setup the Categories and Materiallists, before i start creating categories.
> 
> Are those requirements up to date? (there is nothing about the Block-States) Should they be displayed if a Preset (Lagervorlage) was used?

Not totally, but its is not that important that you define the Progress Labels at the start.
With the layout of the categories it is important, because the layout of the categorie applies only to new activities

**Comment by manuelmeister** [comment]
I've created a visual draft, what I expect the mvp+ version to be:
https://www.figma.com/proto/7zje6DL671LbVOzXmbBIB8/eCamp-Prototypes?page-id=0%3A1&type=design&node-id=86-1226&viewport=163%2C264%2C0.28&t=tew4UCnLrmdSrxNm-1&scaling=min-zoom&starting-point-node-id=86%3A1226&mode=design

Besides that I've created a suggestion to improve the camp creation with #4162 and the category edit #4182

**Comment by BacLuc** [comment]
@manuelmeister 
May we close this issue?
