### ISSUE TITLE
ToDo integrate (Feature Request)

### ISSUE THREAD

**Issue by loelismurf** [ecamp/ecamp3#4281]
Die ToDo Liste mit Aufgaben für eine Lagerplanung welche nicht im Picasso/Zeitplan abefasst werden können.
Habe ich nicht gefunden. Daher wäre gut wenn man das Integrieren könnte
2. Schritt wäre dann auch eine Anbindung an Kalender, Microsoft Planer oder Todoist
Beispiel 
![image](https://github.com/ecamp/ecamp3/assets/77551562/5675d55b-54db-4bc9-a670-c2355f4b70aa)

The ToDo list with tasks for warehouse planning which cannot be entered in the Picasso/schedule.
I have not found it. Therefore it would be good if this could be integrated
2nd step would then also be a connection to calendar, Microsoft planner or Todoist
example 
![image](https://github.com/ecamp/ecamp3/assets/77551562/5675d55b-54db-4bc9-a670-c2355f4b70aa)

**Comment by carlobeltrame** [comment]
Thanks for opening this issue. We have decided not to integrate this feature into eCamp v3, which we also explain in the [FAQ](https://www.ecamp3.ch/de/faq/) on the website. I'll try to elaborate a little here because the FAQ answer is relatively short.

We have discussed this feature in the eCamp core team many times. The last time was in October, where we decided for now not to implement it in eCamp v3. This was for several reasons:
- There are a lot of freely available and commonly used tools for this task, which work much better than an eCamp feature ever could. You mentioned Microsoft Planner, Todoist and general digital calendars yourself, and there is also Trello, Evernote, Google Tasks and even the calendar generator feature in the digital [Hering](https://scout-ch.github.io/hering/#/calendar).
- In order to implement similar features and e.g. syncing with such external tools, we would have to invest a lot of our voluntary developer time, which we would rather use for improving the camp-specific features which currently only eCamp offers.
- eCamp can't and shouldn't be the only tool you use for camp planning. Features like a file storage platform, a budget tool, Höck planning and protocols, management of participants etc. are also clearly out of scope for eCamp, and have to be solved by other tools. The idea is for eCamp to work well with and be integrated well with these other tools, instead of eCamp being the single tool to handle all these tasks. This also matches the [IT guidelines](https://scout-ch.github.io/it-guidelines/#/priciples) of PBS / MSdS / MSS:
  > `4.` Jedes IT-Tool hat einen definierten, möglichst begrenzten thematischen Zweck. Dies erleichtert die Ablösung.
- In most of the camps on eCamp v2, the todo feature wasn't used at all. This further supports the idea that better alternatives already exist.

For these reasons, other features - including new features which eCamp v2 did not have - are currently higher up on the priority list.

**Comment by loelismurf** [comment]
thank you for your detailed explanation.
I totally understand that the volunteer time should be focused on the core.
However, I think the integration of the other tools into ecamp is an important part, maybe not in ecamp itself, but a platform that connects all tools would be good.
Perhaps the PBS also needs to look at how workflows, scheduling and budget planning should look digitally and then combine these in a modular system.

[FAQ of ecamp3](https://www.ecamp3.ch/de/faq/)
