### ISSUE TITLE
template are not updated

### ISSUE THREAD

**Issue by loelismurf** [ecamp/ecamp3#4284]
Nach dem ändern eines Templates wird ein bestehender Block nicht angepasst.
Ist es beabsichtig das Blöcke vom selben Typ nicht aktualisiert werden? Wenn ich beim "alten" auf Layout ändern klicke dann kommt auch das neue Layout nur ändert sich an dem Block nichts. Wäre sicher gut das es mindestens einen Button Layout übernehmen und Layout auf alle Übertragen gebe, falls es überhaupt gewollt ist das es nicht updated.

Vor der Anpassung an dem Layout
![image](https://github.com/ecamp/ecamp3/assets/77551562/59a91232-0ccd-4ec5-97da-7b45780aeaea)
Nach der Anpassung an dem Layout
Bestehende Aktivität ![image](https://github.com/ecamp/ecamp3/assets/77551562/59a91232-0ccd-4ec5-97da-7b45780aeaea)
Neu erstellte Aktivität ![image](https://github.com/ecamp/ecamp3/assets/77551562/d19d0777-a857-42d4-8b54-67ad854c35e0)

After changing a template, an existing block is not updated.
Is it intentional that blocks of the same type are not updated? If I click on Change layout in the "old" block, the new layout is also displayed, but nothing changes in the block. It would certainly be good to have at least one button Apply layout and Transfer layout to all, if it is not intended to be updated at all.

Before adjusting the layout
![image](https://github.com/ecamp/ecamp3/assets/77551562/59a91232-0ccd-4ec5-97da-7b45780aeaea)
After customizing the layout
Existing activity ![image](https://github.com/ecamp/ecamp3/assets/77551562/59a91232-0ccd-4ec5-97da-7b45780aeaea)
Newly created activity ![image](https://github.com/ecamp/ecamp3/assets/77551562/d19d0777-a857-42d4-8b54-67ad854c35e0)

**Comment by carlobeltrame** [comment]
Thanks for reporting. This is expected behaviour as of now, and we consciously deviated from the behaviour of eCamp v2 here.

In eCamp v3, from the user perspective, each activity may have its completely independent layout. Maybe one of your LS activities does not need a safety concept, so you can just remove this piece from only this LS. Maybe you have programme in exactly one of your meal blocks, so you can add a storyboard (3-Spalten-Programm) to just this meal and leave all others untouched. The category is a template in the sense of "copiable blueprint" / "Kopiervorlage", not in the sense of "defines a fixed layout for activities" / "Schablone". You can even add contents to the category, e.g. in the safety concept field of the LS category, you could insert some hints on what to write here when an LS activity is planned, or insert some [commonly used headings](https://pfadi.swiss/media/files/a6/08_sicherheit_de_web.pdf#page=34) which you might want to encourage, etc.

From a technical perspective, allowing each activity to customize the layout and allowing contents (instead of just layout) in the category makes it impossible to algorithmically transfer a changed category layout to all activities of that category.

To inform the users about this, we currently show a message when the category is empty:
![Screenshot 2023-12-20 at 13-22-12 eCamp3](https://github.com/ecamp/ecamp3/assets/7566995/5e98f3e3-1b5a-45ef-b626-ab3b34f9ba23)

In #4182, this message will be promoted so that it is always visible, regardless of the emptyness of the category layout. If you want to help, you can test the new version at https://pr4182.ecamp3.ch/ and let us know how we could make this behaviour more understandable. So far, the prototype looks something like this:
![Screenshot](https://github.com/ecamp/ecamp3/assets/3001985/80788b44-157b-4766-b28b-6e3825c92b2c)

In case you are interested how we got to this feature deviation from eCamp v2: The basis of the flexible activity layout feature was discussed in #834, which itself was a follow-up of improvement ideas discussed in #806.
