### ISSUE TITLE
MaterialNode not rendering items anymore on dev

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#4330]
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/b78a6976-d0c7-41f2-82dc-78da871f6d25)

**Comment by BacLuc** [comment]
May be related to:
![grafik](https://github.com/ecamp/ecamp3/assets/1506818/c3cf2e78-0ebf-45d7-980b-a950253f5b9b)
https://ecamp.sentry.io/issues/4762073820/?project=5602507

**Comment by manuelmeister** [comment]
The bug first occured after https://github.com/ecamp/ecamp3/commit/0680cb8c0230ee14a61dd69de905d90decf0e5be.
It seems that the problem comes from changes to the reactivity part of vue, as these parts have not been changed recently and these errors indicate:

<img width="727" alt="Bildschirmfoto 2023-12-28 um 14 24 36" src="https://github.com/ecamp/ecamp3/assets/3001985/0ff54156-457c-4c6a-8634-ce8969f9217c">
<img width="727" alt="Bildschirmfoto 2023-12-28 um 14 25 01" src="https://github.com/ecamp/ecamp3/assets/3001985/656611d5-973e-41aa-b383-26dc7eda2915">

As I'm not really familiar with the inner workings of the vue reactivity core nor hal-json-vuex, I think it would be sensible if @usu or @carlobeltrame would look at this issue.

**Comment by usu** [comment]
I haven't been able to reproduce locally (in dev mode). Haven't tried in prod/built-mode, yet.

Any of you have been able to reproduce?
@manuelmeister: Where/when did you see the console errors above?

**Comment by BacLuc** [comment]
fixed with https://github.com/ecamp/ecamp3/pull/4342
