### ISSUE TITLE
Define support channel for community

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#527]
Discuss & decide, if at this stage, a community support channel is needed. Possible options:
- ~~Whatsapp~~
- Github Issues with Tagging
- Discord (https://community.vuetifyjs.com/)
- Github Discussions (https://discussions.vuetifyjs.com/)
- Slack
- ... other ideas?

To keep in mind, specific channels might be needed/defined at a later stage for:
- Bug reports & development backlog --> Github Issues
- Community support channel --> this discussion
- Feature requests --> Github issues? or something more end-user friendly such as uservoice?

Other topics:
- [ ] Language: English? Or Englisch/German?

**Comment by usu** [comment]
Discuss & decide, if at this stage, a community support channel is needed. Possible options:
- ~~Whatsapp~~
- Github Issues with Tagging
- Discord
- ... other ideas?


To keep in mind, specific channels might be needed/defined at a later stage for:
- Bug reports & development backlog --> Github Issues
- Community support channel --> this discussion
- Feature requests --> Github issues? or something more end-user friendly such as uservoice?

**Comment by manuelmeister** [comment]
### Discord
#### Pro
- low entry barrier
- different channels
- granular notification settings
- [Vuetify](https://discord.com/invite/s93b7Fv) uses it as well
- separation from issues (in the future we don't want our issues to be cluttered with open non-issues)
- Markdown formatting
- no "issue" housekeeping necessary (if someone has an issue it's probably only relevant today and the next day, otherwise the will post again)
- (video conferencing)

#### Contra
- no direct integration with GitHub
- additional plattform
- no conversation threads

**Comment by usu** [comment]
Github Discussions (Beta) is now activated:
https://github.com/ecamp/ecamp3/discussions

Happy trying it out :-)

**Comment by manuelmeister** [comment]
### Meeting Discuss
Wir versuchen Github Discussion. Wir verwenden Discussions im Moment als Support Channel.
**Sprache**: Im Code und Kommentaren Englisch, in Diskussion frei
