### ISSUE TITLE
ApiStore doesn't trigger reevaluation of computed properties on patch response

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#663]
If I patch an activity, the response contains the patched entity and its embedded entities.

**Expected**
This action triggers to reevaluate a computed property, e.g.
https://github.com/ecamp/ecamp3/blob/7dc333d90e5606bf64d46c89049446b970b2bd53/frontend/src/components/camp/Picasso.vue#L172-L174

**Actual**
It just updates the store (inspected in vue devtools)

I'm not sure if this is working as intended

**Comment by carlobeltrame** [comment]
I think I see why this is happening. Computed properties based on the Vuex store state definitely do update when the Vuex state changes. But in your computed, you ask for `scheduleEntries`, while you say you are patching an activity.

Vue will cache the result of `apiScheduleEntries`, so if you only use the activity outside of the computed, Vue has no way of knowing about that. Vue only keeps track of the dependencies that are accessed inside your computed, i.e. `period` and `scheduleEntries`. As long as there is no change in one of those entities in the Vuex store, Vue will not re-evaluate the computed.

I need to think a bit more about how to solve this correctly. What exactly do you do with the `apiScheduleEntries` that doesn't work?

**Comment by manuelmeister** [comment]
I want to listen for changes to the `scheduleEntries` (and their references like `activity` and its `activityCategory`). On every change, I want to replace the "local" scheduleEntries with the updated entities.

**Comment by carlobeltrame** [comment]
Hm but if the PATCH doesn't change the scheduleEntries at all (and it doesn't, otherwise the computed would update), why would you need to update the "local" schedule entries?

If you really need to reset the schedule entries whenever the activities change, you can either add a watcher for the activities, or you can calculate the scheduleEntries the old way, via activities:
```js
apiScheduleEntries () {
  return this.period().camp().activities().items.flatMap(activity => activity.scheduleEntries().items).filter(scheduleEntry => scheduleEntry.period()._meta.self === this.period()._meta.self())
}, 
```
That way, if any of the activities change, the `apiScheduleEntries` are updated.

**Comment by carlobeltrame** [comment]
Note: If we decided to do ecamp/hal-json-vuex#4, you could just do a deep watcher on apiScheduleEntries. But as of now, since the relations are accessible via functions, a deep watcher wouldn't catch changes in related entities. (for documentation on deep watchers see https://vuejs.org/v2/api/#vm-watch)

**Comment by carlobeltrame** [comment]
An additional note: The deep watcher would indeed work, but I think it would almost work too well. We do have circular references in our entities (e.g. activity -> scheduleEntries -> items[0] -> activity), and we would have to resort to workarounds such as described in https://codeburst.io/caution-using-watchers-for-objects-in-vue-ecafb0af6493

**Comment by carlobeltrame** [comment]
@manuelmeister is this still a problem? ecamp/hal-json-vuex#4 will not be implemented for now.

**Comment by manuelmeister** [comment]
I think we can work around this problem.
