### ISSUE TITLE
xdebug broken on Windows/WSL

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#671]
The following commit breaks debugging on Windows/WSL setup:
https://github.com/ecamp/ecamp3/commit/fbcf816043eb5ef990fcd1fe9906202c2a97c82e

**Why?**
`remote_connect_back=1 `instructs xdebug to connect to the server which triggered the network request.

> If enabled, the xdebug.remote_host setting is ignored and Xdebug will try to connect to the client that made the HTTP request.

Source: https://xdebug.org/docs/all_settings#remote_connect_back

In Windows/WSL setup, the HTTP request is usually made from Windows host (Chrome, Postman, etc.), while the debugger is running in VS Code in the WSL host. 

@manuelmeister @carlobeltrame 
Was this setting necessary for PHPStorm? If yes, do we somehow find a solution that works for both setups without the need to have different Dockerfiles?

**Comment by carlobeltrame** [comment]
On my machine, debugging in PHPStorm also works if `remote_connect_back` is set back to `0` (and I rebuild the backend container). It works in browser requests as well as in tests.

The commit message of @manuelmeister suggests he switched that flag because he had issues with other projects running at the same time. Maybe he can explain his setup. So far we have taken such setups into account, e.g. also with the decision to expose the frontend on port 3000 rather than 80.

**Comment by manuelmeister** [comment]
I need to test again tomorrow.
